### ISSUE TITLE
Использование шаблонов в отдельных файлах совместно с browserfy

### ISSUE THREAD

**Issue by weber** [basisjs/basis-templates#1]
Как использование шаблонов в отдельных файлах совместно с browserfy? (если коротко) Возможно ли это?
Есть директория с файлами шаблонов, подключение их хотелось реализовать с помощью  browserfy.

```
require('./templates/examle.html');
```

ну и работать с ним/и

```
var template = bt('id:example');
```

**Comment by lahmatiy** [comment]
Конечно, возможно. Должно работать такое:

``` js
var template = bt(require('./templates/example.html'));
```

**Comment by weber** [comment]
Спасибо Роман.
